### PR TITLE
modernize libsms

### LINKED ISSUE #1: no popt stops install
if no popt is detected, it should just skip building tools.

### LINKED ISSUE #2: The required library libsndfile could not be found
I'm trying to build under the Homebrew environment on Mac OS X (10.9), and the fundamental problem I'm running into is that Scons doesn't seem to respect pkg-config. Specifically, it doesn't pick up libsndfile when I run `scons` from the shell.

```
scons: Reading SConscript files ...
Checking for C library m... (cached) yes
Checking for C library sndfile... no
The required library libsndfile could not be found
Get it from http://www.mega-nerd.com/libsndfile
```

Even though pkg-config clearly picks it up:

```
$ pkg-config --version libsndfile
0.28
```

Maybe this needs to be fixed in the Scons config file or however it does it? This aside, I think it would compile fine on OS X.

### PR DESCRIPTION
**Pull request by umlaeute**
triggered by a recent discussion on the [Pure Data mailinglist](https://lists.puredata.info/pipermail/pd-dev/2024-04/023608.html) i looked into libsms, and came up with a couple of improvements:

- merge @johnglover 's `master` branch (for the sole reason of trying to avoid divergent forks)
- declare function arguments as `const` whenever possible (mostly motivated by Pd's typechange for symbol strings to `const char*` a decade or so ago; in any case using `const` makes it somewhat easier for a developer to know which pointers are input data, and which are output data - which cannotnot always be guessed easily from the variable-names alone)
- only export the symbols declared in `sms.h` (the rest is *private* and cannot be used outside the library, nor can it conflict with the same symbol in other libraries/hosts) - this fixes a hard crasher bug with Pure Data, at least on Linux (afaik there was no issue on Windows; i don't know about macOS), see https://github.com/pure-data/pure-data/issues/2250 for a symmetric fix in Pd land
- additionally decorate the OOURA symbols to make them local to libsms (in case your compiler does not support hiding symbols)
- consistently use `sfloat` where appropriate (rather than sometimes using `float` for no apparent reason)
- change the buildsystem to `CMake`
    - `scons` is so early naughties that it hurts; apart from that the actual `SConstruct` was full of Python2 idiomatic code that no longer works, now that Py2 has been officially declared dead for > 5 years); oh and it also was full of outdated assumptions on how filesystem layout of the hosts, and other things (like that a Python version consists of up to three characters, so `2.6` is allowed, but `3.12` was stripped to `3.1`...)
- use proper soname versioning (and set the library version to `1.5.0`)
- fix the building of the python module for Python3
- drop trailing whitespace

as a side effect this:
- Closes: #1 
- Closes: #2

### CODE REVIEW

**Comment by richardeakin** [comment]
Now that a large work project has subsided, I can have a go at testing this soon and try to get it merged, if you think it is the best way forward.

Totally agree with the move to CMake, it's clearly become the defacto since this code was originally 'modernized' (when I was in college about 15 years ago).

**Comment by richardeakin** [comment]
@umlaeute I've been working through getting a MinGW / MSYS2 install setup to build this but I could use some help, I'm currently stuck at how to get cmake to use my MSYS2 version of gcc / ninja building - or are you using the MSVC toolchain now? This is virtually all I've ever used on Windows and I'll admitt hat at the time @johnglover added windows support, I was squarely operating from Ubuntu.

I'm currently making progress with:
```
mkdir build
cmake .. -G "Ninja"
```

From the main libsms repo, however it's not picking up my copy of libsndfile that was installed with the official windows 64bit installer from the meganerd website (that installed libsndfile to `C:\Program Files\Mega-Nerd\libsndfile`. I had a quick go at pointing the CMakeCache.txt to this folder but without success, so I was wondering how you've got your configuration where it can find libsndfile.

Thanks again for these updates, looking forward to getting a local copy running here after so many years!

**Comment by umlaeute** [comment]
> or are you using the MSVC toolchain now?

no, I'm a linux guy :-) (so i'm using "Unix Makefiles".

anyhow, i'm not sure i understand your problem.
sorry, if i'm stating the obvious, but with MinGW / MSYS2 you get multiple different environments.
e.g. when you launch the `MSYS2 MSYS` shell, you will not have access to your favorite compiler.
Instead, you should launch the `MSYS MINGW64` shell (or `MSYS CLANG64`) for building Win64 binaries, resp `MSYS MINGW32` for building Win32 binaries.
you will have to install compilers (and libraries) for this specific flavor of MSYS, by prepending `${MINGW_PACKAGE_PREFIX}-` to the components you want to install via `pacman`.
E.g.
```sh
pacman -S ${MINGW_PACKAGE_PREFIX}-toolchain
```
(which is of course equivalent to installing something like `mingw-w64-x86_64-toolchain`, depending on which `MSYS` variant shell you are in).
the `toolchain` is a meta-package, that pulls in the [basic toolchain](https://packages.msys2.org/groups/mingw-w64-x86_64-toolchain) for building, including ` ${MINGW_PACKAGE_PREFIX}-gcc` or ` ${MINGW_PACKAGE_PREFIX}-clang`.

In general, I tend to install the helper-libraries via `pacman` as well, so:
```sh
pacman -S ${MINGW_PACKAGE_PREFIX}-gsl ${MINGW_PACKAGE_PREFIX}-libsndfile
# for whatever reason, we cannot build without Python, so:
pacman -S ${MINGW_PACKAGE_PREFIX}-swig ${MINGW_PACKAGE_PREFIX}-python ${MINGW_PACKAGE_PREFIX}-python-numpy
# if you want to build the documentation
pacman -S ${MINGW_PACKAGE_PREFIX}-doxygen ${MINGW_PACKAGE_PREFIX}-graphviz
```

after that, i can successfully do:
```sh
rm -rf _build; mkdir _build; cd _build
cmake ..
ninja
```

and similar:
```sh
rm -rf _build; mkdir _build; cd _build
cmake .. -G "Unix Makefiles"
make
```


for whatever reasons, the configure-step fails if Python cannot be found, even though it ought to be optional.

**Comment by richardeakin** [comment]
Sorry for the delay on this (I've been on a sort of summer vacation as of late, not in front of a computer much), and thanks for pointing me in the right direction.

I did eventually get the library and tools building on this branch, and they do all run though I've yet to be able to make a proper re-synthesis (the harmonic values from `smsPrint` were bogus from the two sample files I tried, a cat meow and a voice). That said, I'm inclined to merge this as-is since it is a big upgrade and at least gets the project building in modern environments.

I'm also half of a mind to try getting it running using the MSVC toolchain, which I imagine will involve adjusting many of the headers, but as I spend most my time using MSVC that would be the best way for me to debug any runtime issues.

I'll list my install steps here, which we should try to get integrated into the `INSTALL_WINDOWS.md` in some form at some time since that file is out of date now that this project will be using CMake. Note that using the ucrt packages as described [here](https://code.visualstudio.com/docs/cpp/config-mingw#_installing-the-mingww64-toolchain) **did not** work for me, I had to start over with a fresh install using `mingw-w64-x86_64`.

### My Install Steps on Windows 10

- install latest MSYS2 from [here](https://www.msys2.org/)
- add to PATH:
		`C:\msys64\mingw64\bin`
		`C:\msys64\mingw64\lib`
- run `MSYS2 MINGW64` (search MSYS2 via start button)
- install toolchain via pacman:
	- `pacman -S mingw-w64-x86_64-toolchain`
- install cmake via pacman:
	- `pacman -S mingw-w64-x86_64-cmake`
- Extra dependencies via pacman (prefix `pacman -S mingw-w64-x86_64-` to each of these):
	- gsl, libsndfile, popt, swig, python, python-numpy, doxygen, graphviz
- run `cmake .. -G "Ninja" `
- run `ninja`

**Pull request merged**
